export const actionTypes = {
    INCREMENT:'INCREMENT',
    DECREMENT:'DECREMENT',
    PRODUCT_DATA_FATCHING:'PRODUCT_DATA_FATCHING',
    PRODUCT_DATA_SUCCESS:'PRODUCT_DATA_SUCCESS',
    PRODUCT_DATA_FAILED:'PRODUCT_DATA_FAILED',
}